Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/ClassLength:
   Max: 350

Metrics/BlockLength:
  Max: 70

Metrics/AbcSize:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Layout/IndentationWidth:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Enabled: false










